server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/share_bike_db?useSSL=FALSE&useUnicode=TRUE&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 16MB
      max-request-size: 10MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


druid:
  initial-size: 5
  min-idle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: stat,wall,slf4j
  connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
  web-stat-filter:
    enabled: true
    url-pattern: "/*"
    exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  stat-view-servlet:
    url-pattern: "/druid/*"
    allow: 127.0.0.1,192.168.8.109
    deny: 192.168.1.188
    reset-enable: false
    login-username: admin
    login-password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.pojo
  type-handlers-package: com.example.typehandler
